name: Build & publish site

on:
  schedule:
    - cron: "0 7 * * *"     # tous les jours à 07:00 UTC (~09:00 Paris)
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ✅ Remplace 'npm install' par une install robuste + retries
      - name: NPM harden & install (with retries)
        run: |
          set -eux
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 60000
          npm config set audit false
          npm config set fund false

          # petite boucle de retry pour npm ci (max 3 tentatives)
          n=0
          until [ $n -ge 3 ]; do
            npm ci --no-audit --prefer-offline && break
            n=$((n+1))
            echo "npm ci failed ($n) → retry in 10s"
            sleep 10
          done

      # ✅ Installe Playwright + dépendances système, avec retry aussi
      - name: Install Playwright dependencies (with retries)
        run: |
          set -eux
          n=0
          until [ $n -ge 3 ]; do
            npx playwright install --with-deps && break
            n=$((n+1))
            echo "playwright install failed ($n) → retry in 10s"
            sleep 10
          done

      - name: Generate site (scrape + build HTML)
        env:
          MPG_EMAIL: ${{ secrets.MPG_EMAIL }}
          MPG_PASSWORD: ${{ secrets.MPG_PASSWORD }}
          MPG_ESL_FR: ${{ secrets.MPG_ESL_FR }}
          MPG_ESL_UK: ${{ secrets.MPG_ESL_UK }}
          MPG_ESL_ES: ${{ secrets.MPG_ESL_ES }}
          MPG_ESL_IT: ${{ secrets.MPG_ESL_IT }}
          MPG_AUTH_STATE_B64: ${{ secrets.MPG_AUTH_STATE_B64 }}
        run: |
          mkdir -p docs
          node scripts/generate.mjs

      # Dumps Playwright si présents (debug)
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mpg-debug
          path: |
            dump-*.html
            screenshot-*.png
          if-no-files-found: ignore

      # Push des changements (docs/ → Pages)
      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git reset --soft origin/main
          git add docs/ -A
          git commit -m "Update site [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
