name: Build & publish site

on:
  schedule:
    - cron: "0 7 * * *"     # tous les jours à 07:00 UTC (~09:00 Paris la plupart du temps)
  workflow_dispatch: {}      # bouton manuel "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10       # borne le job à 10 minutes max
    permissions:
      contents: write         # autoriser le push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      # Installe navigateurs + dépendances système de Playwright
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Generate site (scrape + build HTML)
        env:
          MPG_EMAIL: ${{ secrets.MPG_EMAIL }}
          MPG_PASSWORD: ${{ secrets.MPG_PASSWORD }}
          MPG_ESL_FR: ${{ secrets.MPG_ESL_FR }}
          MPG_ESL_UK: ${{ secrets.MPG_ESL_UK }}
          MPG_ESL_E
